title: <p align="center"> Sameer Beloshe </p>
logo: assets/img/Sameer.JPG

description:
  <br>
  I am a recent graduate with a Master's degree in Data Analytics and Visualizations, aiming to shape the future of data-driven decisions with AI-powered analytics and scalable engineering solutions.
  <br>
  <a href="assets/img/Sameer_Beloshe_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sameerbeloshe/">LinkedIn</a> |
  <a href="https://github.com/sameerbeloshe">GitHub</a>


  
theme: jekyll-theme-minimal
